accounts:
  - name: alice
    coins: ["2000000000000udws", "1000000wsc"]
  - name: bob
    coins: ["100000000udws"]
build:
  binary: "dewebd"
validator:
  name: alice
  staked: "100000000udws"
client:
  openapi:
    path: "docs/static/openapi.yml"
  vuex:
    path: "vue/src/store"
faucet:
  name: bob
  coins: ["100000udws"]
genesis:
  chain_id: "deweb-testnet-0"
  app_state:
    staking:
      params:
        bond_denom: "udws"
    gov:
      deposit_params:
        min_deposit:
          - amount: "10000000"
            denom: "udws"
    mint:
      params:
        mint_denom: "udws"
    token: 
      params: 
        token_tax_rate: "0.400000000000000000"
        issue_token_base_fee: 
          denom: "dws"
          amount: "1000"
        mint_token_fee_ratio: "0.100000000000000000"
    crisis:
      constant_fee:
        amount: "100000000",
        denom: "udws"
